export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_ARTICLE_FEEDS_REQUEST = "GET_ARTICLE_FEEDS_REQUEST";
export const GET_ARTICLE_FEEDS_SUCCESS = "GET_ARTICLE_FEEDS_SUCCESS";
export const GET_ARTICLE_FEEDS_FAILURE = "GET_ARTICLE_FEEDS_FAILURE";

export const GET_TEAMS_REQUEST = "GET_TEAMS_REQUEST";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILURE = "GET_TEAMS_FAILURE";

export const GET_CONTEST_ID_REQUEST = "GET_CONTEST_ID_REQUEST";
export const GET_CONTEST_ID_SUCCESS = "GET_CONTEST_ID_SUCCESS";
export const GET_CONTEST_ID_FAILURE = "GET_CONTEST_ID_FAILURE";
