export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_ARTICLE_FEEDS_REQUEST = "GET_ARTICLE_FEEDS_REQUEST";
export const GET_ARTICLE_FEEDS_SUCCESS = "GET_ARTICLE_FEEDS_SUCCESS";
export const GET_ARTICLE_FEEDS_FAILURE = "GET_ARTICLE_FEEDS_FAILURE";

export const GET_TIMELINE_FEEDS_REQUEST = "GET_TIMELINE_FEEDS_REQUEST";
export const GET_TIMELINE_FEEDS_SUCCESS = "GET_TIMELINE_FEEDS_SUCCESS";
export const GET_TIMELINE_FEEDS_FAILURE = "GET_TIMELINE_FEEDS_FAILURE";
